### ISSUE TITLE
Multi-threading?

### ISSUE THREAD

**Issue by mrdrgz** [shenkers/isoscm#11]
I've observed that when running isoscm, there's around 19 child processes out of it. Is there any way to control how many threads you want it to use?

Note: I'm not very familiar with java overall, maybe there's something very obvious I'm missing.

**Comment by shenkers** [comment]
IsoSCM is not multi-threaded by design, it runs on a single java thread. When I grep for the process ID I don't see other child processes coming up. If I run 'top' I see that the IsoSCM process is taking up 100% of one CPU, suggesting that it's not using more than one thread. Can you provide a little more information about what you have done? The java runtime environment uses multiple threads (eg for garbage collection http://stackoverflow.com/questions/9916399/how-many-threads-does-the-jvm-fork-when-it-is-started ), maybe these are the processes you are seeing?

**Comment by mrdrgz** [comment]
I checked that with htop. The other processes are consuming 0 cpu and the exact same memory as the main process, so i guess it matches those java runtime threads :) Thanks!

**Comment by shenkers** [comment]
cool :)
