### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by arefeen** [shenkers/isoscm#16]
I am using single end reads having length 75bp. While running the tool, I have got the below exception. Therefore can you please tell me how to get rid of this exception. The corresponding sam file of the input bam file has 12 columns. The last column contains only the tag XS. The value of XS is either "XS:A:+" or "XS:A:-" based on the strand of gene with which the read is mapped.

Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
        at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:648)
        at htsjdk.samtools.SAMRecord.getFirstOfPairFlag(SAMRecord.java:706)
        at tools.BAMTools.strand(BAMTools.java:1022)
        at processing.FindSpliceJunctions.tabulateSpliceJunctions(FindSpliceJunctions.java:135)
        at executable.IsoSCM.main(IsoSCM.java:240)

**Comment by shenkers** [comment]
Could you please post all the log messages and the command you used to run
IsoSCM?

**Comment by arefeen** [comment]
Initially I run the tool using the following command:
java -Xmx2048m -jar IsoSCM-2.0.12.jar assemble -bam simulated_mapped_read_modified.sorted.bam -base simu_tool -s reverse_forward
At that time I got the above exception and the log file output was:
12:54:33.090 [main] INFO  executable.IsoSCM - IsoSCM 2.0.12
12:54:33.136 [main] INFO  executable.IsoSCM - Command: java -jar -Xmx2048m IsoSCM-2.0.12.jar assemble -bam simulated_mapped_read_modified.sorted.bam -base simu_tool -s reverse_forward
12:54:33.248 [main] INFO  executable.IsoSCM - Starting assemble ...
12:54:33.468 [main] INFO  executable.IsoSCM - tabulating splice junctions...

After that I have run the tool using the following command:
java -Xmx2048m -jar IsoSCM-2.0.12.jar assemble -bam simulated_mapped_read_modified.sorted.bam -base simu_tool -s unstranded 
At this point I have got some output and the log file output is:

14:54:20.020 [main] INFO  executable.IsoSCM - IsoSCM 2.0.12
14:54:20.060 [main] INFO  executable.IsoSCM - Command: java -jar -Xmx2048m IsoSCM-2.0.12.jar assemble -bam simulated_mapped_read_modified.sorted.bam -base simu_tool -s unstranded
14:54:20.164 [main] INFO  executable.IsoSCM - Starting assemble ...
14:54:20.385 [main] INFO  executable.IsoSCM - tabulating splice junctions...
14:54:27.509 [main] INFO  executable.IsoSCM - counting junction supporting reads...
14:58:45.003 [main] INFO  executable.IsoSCM - identifying covered segments...
14:59:24.527 [main] INFO  executable.IsoSCM - merging coverage gaps less than 100 bp...
14:59:24.832 [main] INFO  executable.IsoSCM - filtering splice junctions...
14:59:25.590 [main] INFO  executable.IsoSCM - inferring segment strand from spliced reads...
14:59:25.747 [main] INFO  executable.IsoSCM - identifying spliced exons...
14:59:25.926 [main] INFO  executable.IsoSCM - trimming exons that overlap on opposite strands...
14:59:26.015 [main] INFO  executable.IsoSCM - identifying change points...
14:59:32.723 [main] INFO  executable.IsoSCM - filtering change points close to splice junctions...
14:59:32.826 [main] INFO  executable.IsoSCM - enumerating change point exons...
14:59:32.865 [main] INFO  executable.IsoSCM - identifying connected components...
14:59:33.023 [main] INFO  executable.IsoSCM - identifying unspliced segments...
14:59:33.072 [main] INFO  executable.IsoSCM - calculating coverage...
14:59:57.000 [main] INFO  executable.IsoSCM - assemble completed.

**Comment by shenkers** [comment]
Awesome, thank you. Can I ask, is your data stranded or not?

**Comment by arefeen** [comment]
Well, the reads are generated from both positive and negative strand genes.

**Comment by arefeen** [comment]
If you want I can share the simulated data.

**Comment by shenkers** [comment]
Sure, if you post the file I'd be happy to look at it. The strandedness
depends on how the sample was prepared, this link explains some possible
alternatives:

https://www.biostars.org/p/64250/

If you're simulating reads, you can decide which protocol you would like
to emulate.

**Comment by shenkers** [comment]
I'm going to close this since it looks like IsoSCM runs correctly if you run in unstranded mode, and I'm assuming it was a problem with assigning the strandedness parameter

**Comment by arefeen** [comment]
My simulation reads have values like "XS:A:+" and "XS:A:-". I think this
means the data is stranded. But with the reverse_forward the tool gives
error.

On Tue, Feb 16, 2016 at 2:19 PM, shenkers <notifications@github.com> wrote:

> I'm going to close this since it looks like IsoSCM runs correctly if you
> run in unstranded mode, and I'm assuming it was a problem with assigning
> the strandedness parameter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shenkers/isoscm/issues/16#issuecomment-184898193>.
>



-- 
Thanks & Regards,

Ashraful Arefeen
Email: ashraful.arefeen@csebuet.org

**Comment by shenkers** [comment]
The error is caused because the 'reverse_forward' strandedness implies input reads are paired-end, but the appropriate bits are not set in the FLAG field of the sam record. For a specification of how the flag should be set see https://samtools.github.io/hts-specs/SAMv1.pdf. For a read to be paired end it should have the 0x1 bit set (multiple segments, ie two reads in the pair), one of the 0x40 or 0x80 bits set (specifying whether the read is the 1st/2nd read in the pair), and 0x10 or 0x20 set (specifying whether
the read and its pair align to the plus/minus strand). To simulating reads that are compatible with the reverse_forward mode, the read orientations should look something like this:

2nd read FLAG:  0x1 = 1; 0x40 = 0; 0x80 = 1; 0x10 = 0; 0x20 = 1
1st read FLAG: 0x1 = 1; 0x40 = 1; 0x80 = 0; 0x10 = 1; 0x20 = 0

|>>>>>>>gene>>>>>>> gene on plus strand
..................<---............... 1st read  
.......--->.......................... 2nd read                                

The read pairs always 'face-towards' each other, with the 1st read coming
from the opposite strand of the transcript, and the 2nd read aligning to
the same strand as the transcript. If you share a sample of your simulated
bam file I can verify that it is in the correct format.
