### ISSUE TITLE
ADAM format support

### ISSUE THREAD

**Issue by antonkulaga** [shenkers/isoscm#2]
Support for ADAM format ( http://bdgenomics.org/projects/adam/ )will be very helpful, not only because it is better than BAM but also because there are some nice libs that can be used for pre- and post- processing

**Comment by shenkers** [comment]
Hi Anton,

IsoSCM uses BAM formatted files because that is a community standard for short read alignments, making it easily compatible with existing alignment tools. Since it looks like ADAM supports transformation to BAM, I do not see a reason for IsoSCM to support ADAM format natively at this time.
