### ISSUE TITLE
How to use IsoSCM GTFs as input files for DEXSeq 

### ISSUE THREAD

**Issue by qoiopipq** [shenkers/isoscm#20]
I used IsoSCM to identify alternative 3' UTRs with different lengths in different tissue types(output files are GTFs containing tissue specific 3' UTRs), then I want to quantify the differential usage of these alternative 3' UTRs across different tissue types. I know that neither Ensembl nor UCSC GTF reference file contains the tissue specific 3' UTRs, so I tried to re-annotate IsoSCM output GTF files with reference GTF. The idea is that I want to get a GTF file containing all tissue specific 3' UTRs, which can be used for the following dexseq_count step.

But, if multiple 3' UTRs/terminal exons (same start site, different stop sites) are annotated with same transcript ID, dexseq_prepare_annotation will only include the longest one in the GFF output.
I've got 3 tissue types in my analysis: thymus, liver and spleen.
Here is an example of two possible 3' UTRs of gene Fubp1 in thymus GTF file:
_chr3   sol exon    152232395   152233253   .   +   .   gene_id "Fubp1"; gene_name "Fubp1"; p_id "P24872"; transcript_id "NM_057172"; tss_id "TSS5999";
chr3    sol exon    152232395   152232485   .   +   .   gene_id "Fubp1"; gene_name "Fubp1"; p_id "P24872"; transcript_id "NM_057172"; tss_id "TSS5999";_

Two different 3' UTRs of gene Fubp1 in liver GTF file:
_chr3   sol exon    152232395   **152233965**   .   +   .   gene_id "Fubp1"; gene_name "Fubp1"; p_id "P24872"; transcript_id "NM_057172"; tss_id "TSS5999";
chr3    sol exon    152232395   152233885   .   +   .   gene_id "Fubp1"; gene_name "Fubp1"; p_id "P24872"; transcript_id "NM_057172"; tss_id "TSS5999";_

One more 3' UTR of gene Fubp1 in spleen GTF file:
_chr3   sol exon    152232395   152232532   .   +   .   gene_id "Fubp1"; gene_name "Fubp1"; p_id "P24872"; transcript_id "NM_057172"; tss_id "TSS5999";_

After merging them and put through dexseq_prepare_annotation step, I only got one exon to represent 3' UTR:
_chr3   dexseq_prepare_annotation.py    exonic_part 152232395   **152233965**   .   +   .   transcripts "NM_057172"; exonic_part_number "018"; gene_id "Fubp1"_

So, I am wondering how can I include all alternative 3' UTRs in the GFF file, then I can use it to count for the usage of these alternative 3' UTRs ??

Although this isn't a question directly related to IsoSCM, any ideas will be appreciated.

**Comment by shenkers** [comment]
Hi @qoiopipq, you mention that you are merging the models before using the dexseq_prepare_annotation step, what are you using to merge the models? Is this cuffmerge? Also, I believe DEXSeq requires replicates in order to perform differential expression analysis. Do you have replicates for your samples?

I would recommend using the output of the compare step as the input for DEXSeq. Since you will have replicates of each condition, I would merge all replicates of the same tissue type together, and run assemble on the merged samples, for each pair of conditions you can run the compare step on the output of assemble. One of the outputs is a .gtf file that lists the locations of change-points. Each locus has a unique id, and any change-point in that locus receives the same locus id. If you load this file in IGV you will see something like this:

![compare_example](https://cloud.githubusercontent.com/assets/2341961/15327294/f4896b44-1c1e-11e6-8efd-4cb89ba85506.png)

For each locus you could output a set of annotation for DEXSeq, where you would include the entire locus as the long isoform, and each change-point would correspond to a short isoform from the 5'end of the locus to the position of the change-point. DEXSeq needs the annotations to be given correct gene_id and transcript_id attributes so that it knows how to perform the differential expression analysis. You could use the locus id to give each set of alternative isoforms a common gene_id, and then give each alternative 3'UTR a distinct transcript_id. To give you an idea what this would look like I've drawn some lines to represent the isoforms you would output for this locus, and indicated the fields you would want to include in the GTF for the DEXSeq analysis.

![compare_example](https://cloud.githubusercontent.com/assets/2341961/15327906/18de3a36-1c21-11e6-93f3-1f4a0577318b.png)

Let me know if there is anything else I can help with.

**Comment by qoiopipq** [comment]
Thanks for your detailed explanation!!!
I used the output from compare step (just thymus vs liver for testing my script). I managed to generate a gtf file has distinct transcript_ids for 3'UTRs that sharing same gene_id. Then I was able to get the GFF from dexseq_prepare_annotation step. 

This the gene Fubp1 example - gtf output from compare step:
![screen shot 2016-05-18 at 3 32 38 pm](https://cloud.githubusercontent.com/assets/16911467/15348561/3429e936-1d0f-11e6-91b7-9f15e55e2638.png)

So, there are two possible 3' UTRs in the modified gtf file (test_pos.gtf): 
![screen shot 2016-05-18 at 3 36 11 pm 2](https://cloud.githubusercontent.com/assets/16911467/15348883/a7b8afe8-1d11-11e6-9450-614a73b20f40.png)
And in the gff output from the dexseq_preppare_annotation, it takes the longest isoform as "aggregate gene" and then just splits this longest isoform into two parts according to the change-point location. 
I haven't done dexseq_count step, but the gff file looks quite ok to me, not sure whether I'm on the right track or not. 

Cheers
