### ISSUE TITLE
UTR extraction

### ISSUE THREAD

**Issue by antonkulaga** [shenkers/isoscm#4]
It is not clear for me how to extract UTRs from assembled data, as I undestand 3p and 5p exons contain both UTRs and CDS, right? I will be happy to see some explanation in readme about using the tool for UTR extraction.

P.S. I am sorry if I confused something. I noticed isoscm when I was searching for a tool for my task (extracting UTRs from transcripts, unfortunately RNASeq assemblers give my only exons in most of the cases)

**Comment by cyrilcros** [comment]
It is not included yet in the software (but it should, I think). I recommend you get a BED file with the position of the CDS (the annotation is always correct....). You can then use some Bedtools operations:
bedtools merge the different exons of your Isoscm gtf files which form a same gene (they are next to each other). Use bedtools substract using the CDS bed file, leaving you with this structure: 5'/ a hole corresponding to the cds/3'.
To finish, use bedtools closest with this last file and the CDS bed file to get the closest features to the right of each cds. You get the 3' of each cds this way. Use bedtools intersect on the original Isoscm file and you are left with only the 3' features (exons and introns).

IsoSCM is a bit unwieldy in that it does not allow you to match your transcripts to the official annotation directly, or retrieve the 5'and 3'. You have to use bedtools to do this.

Also, Cufflinks is not as good at identifying 3' but it is generates a rather nice annotation with Ensembl Gene IDs. You can use bedtools merge/intersect to keep the Isoscm annotation but include the Cufflinks data.

**Comment by mrdrgz** [comment]
Hi,

Is it in the future plans to add some code to match to existing annotation / use existing annotation to compute 3'UTR usages?

**Comment by shenkers** [comment]
since 2.0.9 there is a 'diff' command that you can use to compare the IsoSCM output with a reference annotation. 

To run the 'diff' command type:

java -jar IsoSCM-2.0.9.jar diff -x [ compare_paramters.xml from compare step ] -G [ reference gene models GTF ]

The reference gene models have to use the same format as the Ensembl GTFs ( http://useast.ensembl.org/info/data/ftp/index.html ), ie they need "gene_id" and "transcript_id" attributes delimited using the same spacing characters. If you use gene models from another source you need to make sure that they match the Ensembl format or they will not be parsed correctly.

The output of this command will be a table with columns:

exon - the terminal exon from the compare command
locus_id - the locus_id, corresponding to the output of the compare command
match_5p_3p - the transcript_id's of reference models that match both the 5' and 3' boundaries of the assembled exon
match_5p_3p_type - the relative location of the matching exon in the reference transcript
match_5p - the transcript_id's of reference models that match only the 5' boundaries of the assembled exon
match_5p_type - the relative location of the matching exon in the reference transcript
match_3p - the transcript_id's of reference models that match only the 3' boundaries of the assembled exon
match_3p_type - the relative location of the matching exon in the reference transcript
overlaps - the transcript_id's of reference models that overlap the assembled exon
overlaps_type - the relative location of the matching exon in the reference transcript
The reference exon types will be one of [ 5p_exon, internal_exon, 3p_exon ] if it comes from a spliced transcript, and unspliced if the reference model is a single-exon transcript. While it is possible that IsoSCM will assemble novel 3'-terminal exons that were never previously annotated, the most conservative approach would be to focus on terminal exons that are consistent with existing gene models. You can do this by filtering for rows that have a match_5p_type of 3p_exon, to select loci that exactly match the 5' boundary of an annotated terminal exon.

IsoSCM won't use an existing annotation to compute alternative 3'UTR usage. If you are only interested in existing annotations tools such as MISO or DEXSeq will do exactly this. However, sometimes the reference annotation does not contain annotations for the alternative 3'UTR isoforms, which motivates using a tool like IsoSCM which allows you to identify and quantify the alternative isoforms directly from RNA-seq data.
